// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfZ2bM2uUwWeYE7Qzx89Ac0ZzJIUuaDHs',
    appId: '1:177156931080:android:92c1e2cb46ff6f38211bbd',
    messagingSenderId: '177156931080',
    projectId: 'flutter-expert-dicoding-c1263',
    storageBucket: 'flutter-expert-dicoding-c1263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFLvTLUTU8YViiTNK61JgaSDQxB_1dwMY',
    appId: '1:177156931080:ios:4b1383b55176c765211bbd',
    messagingSenderId: '177156931080',
    projectId: 'flutter-expert-dicoding-c1263',
    storageBucket: 'flutter-expert-dicoding-c1263.appspot.com',
    iosClientId: '177156931080-hknpb9j9v762d3uhmjqlgd7njo4qe7m9.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
